pipeline:
  type: Ingest

  location_id: nwtc
  dataset_name: flux_z01
  qualifier: flux
  # temporal: 10min
  data_level: a1

dataset_definition:
  attributes:
    title: Example Ingest for awaken surface flux sonics
    description: Example Ingest for awaken surface flux sonics
    conventions: "ME Data Pipeline Standards: Version 1.0"
    institution: National Renewable Energy Laboratory
    code_url: https://github.com/tsdat/ingest-template-local
    location_meaning: National Wind Technology Center

  dimensions:
    time:
        length: unlimited
    height:
        length: 2

  variables:

    time:
      input:
        name: TIMESTAMP
        converter:
          classname: tsdat.utils.converters.StringTimeConverter
          parameters:
            timezone: UTC
            time_format: "%Y-%m-%d %H:%M:%S"
      dims: [time]
      type: long
      attrs:
        long_name: Time (UTC)
        standard_name: time
        units: seconds since 1970-01-01T00:00:00

    height:
      data: [3,7]
      dims: [height]
      type: int
      attrs:
        long_name: Height ASL
        units: m

    U_ax:
      dims: [time, height]
      type: float
      input:
        name: U_ax
      attrs:
        long_name: Wind Speed in U direction
        description: "Wind speed is the measurement of how fast wind is moving past a 
        fixed location in the horizontal plane. The lidar wind profiler, which is 
        mounted on the buoy hull, measures wind speed at heights between 40 m to 250 
        meters above the sea surface by detecting the reflection of laser signals sent 
        into the atmosphere."
        standard_name: wind_speed
        units: m/s

    V_ax:
      dims: [time, height]
      type: float
      input:
        name: V_ax
      attrs:
        long_name: Wind Speed in V direction
        description: "Wind speed is the measurement of how fast wind is moving past a 
        fixed location in the horizontal plane. The lidar wind profiler, which is 
        mounted on the buoy hull, measures wind speed at heights between 40 m to 250 
        meters above the sea surface by detecting the reflection of laser signals sent 
        into the atmosphere."
        standard_name: wind_speed
        units: m/s

    W_ax:
      dims: [time, height]
      type: float
      input:
        name: W_ax
      attrs:
        long_name: Wind Speed in W direction
        description: "Wind speed is the measurement of how fast wind is moving past a 
        fixed location in the horizontal plane. The lidar wind profiler, which is 
        mounted on the buoy hull, measures wind speed at heights between 40 m to 250 
        meters above the sea surface by detecting the reflection of laser signals sent 
        into the atmosphere."
        standard_name: wind_speed
        units: m/s

    Ts:
      dims: [time, height]
      type: float
      input:
        name: Ts
      attrs:
        long_name: Tempurature
        description: "Air temperature measures how hot or cold the atmosphere is at the 
        location of the sensor."
        standard_name: Ts
        units: degC

    Record:
      dims: [time]
      type: float
      input:
        name: RECORD

#-----------------------------------------------------------------
quality_management:

  #---------------------------------------------------------------
  manage_missing_coordinates:
    checker:
      classname: tsdat.qc.checkers.CheckMissing
    handlers:
      - classname: tsdat.qc.handlers.FailPipeline
    variables:
      - COORDS

  manage_coordinate_monotonicity:
    checker:
      classname: tsdat.qc.checkers.CheckMonotonic
    handlers:
      - classname: tsdat.qc.handlers.FailPipeline
    variables:
      - COORDS

  #---------------------------------------------------------------
  manage_missing_values:
    checker:
      classname: tsdat.qc.checkers.CheckMissing
    handlers:
      - classname: tsdat.qc.handlers.RemoveFailedValues
      - classname: tsdat.qc.handlers.RecordQualityResults
        parameters:
          bit: 1
          assessment: Bad
          meaning: "Value is equal to _FillValue or NaN"
    variables:
      - DATA_VARS

  manage_fail_min:
    checker:
      classname: tsdat.qc.checkers.CheckFailMin
    handlers:
      - classname: tsdat.qc.handlers.RecordQualityResults
        parameters:
          bit: 2
          assessment: Bad
          meaning: "Value is less than fail_range"
    variables:
      - DATA_VARS

  manage_fail_max:
    checker:
      classname: tsdat.qc.checkers.CheckFailMax
    handlers:
      - classname: tsdat.qc.handlers.RecordQualityResults
        parameters:
          bit: 3
          assessment: Bad
          meaning: "Value is greater than fail_range"
    variables:
      - DATA_VARS
